### ISSUE TITLE
JSON View has a security issue. Use JSON Viewer

### ISSUE THREAD

**Issue by cofauver** [SF-WDI-LABS/js-objects#1]
From the JSON View reviews:

![image](https://cloud.githubusercontent.com/assets/6520345/23717933/a0001bea-03ea-11e7-8f9b-f90eb4c8307a.png)

[source](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc/reviews?hl=en)

Instead use [JSON Viewer](https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh?hl=en)

**Comment by mnfmnfm** [comment]
It appears that this is no longer the case, and JSONView is working as expected. Closing the issue.
